//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTovar
    {
        public int Id { get; set; }
        public int sum { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
